# Generated by Django 3.1.7 on 2021-03-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0002_customkorisnici_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customkorisnici',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/mypage/images/profile_image.png', null=True, upload_to='images/'),
        ),
    ]
