# Generated by Django 3.1.5 on 2021-03-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0006_auto_20210312_1236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentUserMajstor',
        ),
    ]
