# Generated by Django 3.1.5 on 2021-03-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0008_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Mid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
